baseURL = "https://aim-datamining.github.io"
contentDir = "content"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "HappyDay - Emotion recognition"
theme = "docdock"
#themesdir = "../.."
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[params]
editURL = "https://github.com/AIM-DataMining/aim-datamining.github.io"
showVisitedLinks = true # default is false
themeStyle = "flex" # "original" or "flex" # default "flex"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window
enableGitInfo = true

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> <label>Github repo</label>"
identifier = "ds"
url = "https://github.com/AIM-DataMining"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-cloud-download'></i> <label>Download Service</label>"
url = "https://github.com/ofesseler/happy-day-service/releases"
weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-cloud-download'></i> <label>Download App</label>"
url = "https://play.google.com/store/apps/details?id=de.data_mining.hs_esslingen.happyday"
weight = 12

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> <label>Credits</label>"
url = "/credits"
weight = 30
